name: npm-publish
on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0
    - name: Yarn
      run: yarn
    - name: Yarn lint
      run: yarn lint
    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@f93f535ece805e795c958019e90c63cbb2db326e
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^Release (\\S+)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


